# CMake generated Testfile for 
# Source directory: /home/jakub/FIT-2016-2019/IVS/Project1/assignment
# Build directory: /home/jakub/FIT-2016-2019/IVS/Project1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(emptyBinaryTreeTest.isEmpty "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=emptyBinaryTreeTest.isEmpty")
add_test(emptyBinaryTreeTest.InsertPositiveNode "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=emptyBinaryTreeTest.InsertPositiveNode")
add_test(emptyBinaryTreeTest.InsertnegativeNode "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=emptyBinaryTreeTest.InsertnegativeNode")
add_test(emptyBinaryTreeTest.DeleteNode "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=emptyBinaryTreeTest.DeleteNode")
add_test(emptyBinaryTreeTest.FindNode "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=emptyBinaryTreeTest.FindNode")
add_test(BinaryTreeTest.isNotEmpty "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=BinaryTreeTest.isNotEmpty")
add_test(BinaryTreeTest.InsertNode "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=BinaryTreeTest.InsertNode")
add_test(BinaryTreeTest.DeleteNode "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=BinaryTreeTest.DeleteNode")
add_test(BinaryTreeTest.FindNode "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=BinaryTreeTest.FindNode")
add_test(AxiomsTest.LeafNodesColor "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=AxiomsTest.LeafNodesColor")
add_test(AxiomsTest.AllNodesColor "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=AxiomsTest.AllNodesColor")
add_test(AxiomsTest.PathToRoot "/home/jakub/FIT-2016-2019/IVS/Project1/black_box_test" "--gtest_filter=AxiomsTest.PathToRoot")
add_test(oneMatrix.defaulConstructor "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.defaulConstructor")
add_test(oneMatrix.constructor "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.constructor")
add_test(oneMatrix.setOnevalue "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.setOnevalue")
add_test(oneMatrix.setAllvalues "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.setAllvalues")
add_test(oneMatrix.get "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.get")
add_test(moreMatrixs.equalMatrix "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.equalMatrix")
add_test(moreMatrixs.notEqualMatrixThrow "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.notEqualMatrixThrow")
add_test(moreMatrixs.notEqualMatrix "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.notEqualMatrix")
add_test(moreMatrixs.add_1x1 "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.add_1x1")
add_test(moreMatrixs.add_1x1_Throw "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.add_1x1_Throw")
add_test(moreMatrixs.multiply_1x1 "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.multiply_1x1")
add_test(moreMatrixs.multiply_1x1_Throw "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.multiply_1x1_Throw")
add_test(moreMatrixs.Add "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.Add")
add_test(moreMatrixs.multiply "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.multiply")
add_test(moreMatrixs.multiplyByConst "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.multiplyByConst")
add_test(moreMatrixs.solveThrows "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=moreMatrixs.solveThrows")
add_test(oneMatrix.solve_1x1 "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.solve_1x1")
add_test(oneMatrix.solve_2x2 "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.solve_2x2")
add_test(oneMatrix.solve_2x2_negative "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.solve_2x2_negative")
add_test(oneMatrix.solve_2x2_float "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.solve_2x2_float")
add_test(oneMatrix.solve_3x3 "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.solve_3x3")
add_test(oneMatrix.solve_3x3_float "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.solve_3x3_float")
add_test(oneMatrix.solve "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.solve")
add_test(oneMatrix.solve_float "/home/jakub/FIT-2016-2019/IVS/Project1/white_box_test" "--gtest_filter=oneMatrix.solve_float")
add_test(NonEmptyQueue.Insert "/home/jakub/FIT-2016-2019/IVS/Project1/tdd_test" "--gtest_filter=NonEmptyQueue.Insert")
add_test(NonEmptyQueue.RemoveAllForward "/home/jakub/FIT-2016-2019/IVS/Project1/tdd_test" "--gtest_filter=NonEmptyQueue.RemoveAllForward")
add_test(NonEmptyQueue.RemoveAllBackward "/home/jakub/FIT-2016-2019/IVS/Project1/tdd_test" "--gtest_filter=NonEmptyQueue.RemoveAllBackward")
add_test(NonEmptyQueue.Find "/home/jakub/FIT-2016-2019/IVS/Project1/tdd_test" "--gtest_filter=NonEmptyQueue.Find")
add_test(EmptyQueue.Insert "/home/jakub/FIT-2016-2019/IVS/Project1/tdd_test" "--gtest_filter=EmptyQueue.Insert")
add_test(EmptyQueue.Remove "/home/jakub/FIT-2016-2019/IVS/Project1/tdd_test" "--gtest_filter=EmptyQueue.Remove")
add_test(EmptyQueue.Find "/home/jakub/FIT-2016-2019/IVS/Project1/tdd_test" "--gtest_filter=EmptyQueue.Find")
add_test(NonEmptyQueue.myremove "/home/jakub/FIT-2016-2019/IVS/Project1/tdd_test" "--gtest_filter=NonEmptyQueue.myremove")
subdirs(googletest-build)
